-- Add migration script here
INSERT INTO `catcoin_reward` (`name`, `file`, `rarity`) VALUES
("Pounce the Cat (Hunting Position)", "public/pounce_hunting.png", "Rare"),
("American Eskimo (Tame Position)", "public/eskimo_tame.png", "Fluffy"),
("American Eskimo (Attack Position)", "public/eskimo_attack.png", "Rare"),
("American Eskimo (Defense Position)", "public/eskimo_defense.png", "Common"),
("Corgi (Attack Position)", "public/corgi_attack.png", "Common"),
("Corgi (Tame Position)", "public/corgi_tame.png", "Common"),
("Pitbull (Attack Position)", "public/pitbull_attaack.png", "Common"),
("Pitbull (Tame Position)", "public/pitbull_tame.png", "Rare"),
("Random Fucking Plastic Horse (Attack Position)", "public/horse_attack.png", "Peak"),
("Pomeranian Pup (Tame Position)", "public/pomeranian_tame.png", "Common"),
("Pomeranian Pup (Attack Position)", "public/pomeranian_attack.png", "Rare"),
("Pomeranian Pup (Defense Position)", "public/pomeranian_defense.png", "Common"),
("Basset Hound (Attack Position)", "public/basset_attack.png", "Rare"),
("Basset Hound (Defense Position)", "public/basset_defense.png", "Common"),
("Basset Hound (Tame Position)", "public/basset_tame.png", "Fluffy"),
("Dog Gang (Attack Position)", "public/dog_gang_attack.png", "Peak"),
("Border Collie (Attack Position)", "public/border_attack.png", "Common"),
("Border Collie (Defense Position)", "public/border_defense.png", "Common"),
("Border Collie (Tame Position)", "public/border_tame.png", "Rare"),
("Boxer Pup (Tame Position)", "public/boxer_tame.png", "Rare"),
("Boxer Pup (Seated Position)", "public/boxer_seated.png", "Common"),
("Giraffe (Defense Position)", "public/giraffe_defense.png", "Rare"),
("Webkinz Cat (Sopping Position)", "public/cat_sopping.png", "Peak"),
("Siamese Cat (Seated Position)", "public/siamese_seated.png", "Rare");
