name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: sarah-vps
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} . || true
          git pull

      - name: Build
        run: |
          source ~/.profile
          cargo sqlx migrate run
          cargo build --release

      - name: Run
        run: |
          sudo supervisorctl restart girlpound-bot
