name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: sarah-vps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Build
        run: |
            cargo sqlx migrate run
            cargo build --release

      - name: Run
        run: |
            sudo supervisorctl restart girlpound-bot
